const mongoose = require("mongoose")
const Invoice = new mongoose.Schema({
  userId:{
    type:String,
    required:true
  },
  sender:{
    type:String,
    required:true
  },
  date:{
    type:String,
    required:true
  },
  vehicle:{
    type:String,
    required:true
  },
  plat:{
    type:String,
    required:true
  },
  vehicleType:{
    type:String,
    required:false
  },
  client:{
    type:String,
    required:false
  },
  phoneNumber:{
    type:String,
    required:true
  },
  diagnosis:{
    type:String,
    required:true
  },
  action:{
    type:String,
    required:true
  },
  spareParts:{
    type:String,
    required:false
  },
  sparePartsPrice:{
    type:String,
    required:false,
    default:"-"
  },
  freonUse:{
    type:String,
    default:"-"
  },
  repairService:{
    type:String,
    required:true
  },
  total:{
    type:String,
    required:true
  },
  desc:{
    type:String,
    default:"-"
  }
},{timestamps:true})

module.exports = new mongoose.model('Invoice',Invoice)
